[[redirects]]
  from = "https://misaka-vue.netlify.app"
  to = "https://misaka-fans.space"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  conditions = {Path= ["!^/about", "!^/imgboard", "!^/discuss", "!^/aboutrailgun", "!^/resource", "!^/awards", "!^/relationship", "!^/links"]} 
