[[redirects]]
  from = "https://misaka-vue.netlify.app"
  to = "https://misaka-fans.space"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  conditions = {Path: "!^/about"}
  status = 200
  force = true
